apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leader-bot-ingress
  namespace: leader-bot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "4M"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /leader/webhook/leader-bot(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: leader-bot-service
            port:
              number: 8000
