apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leader-bot-ingress
  namespace: leader-bot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /leader(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: leader-bot-service
            port:
              number: 8000
